name: CI

on:
  pull_request:

jobs:

  lint-imports:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Load requirements cache, if present
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/testing.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/edx/testing.txt

    - name: Analyze imports within root packages
      run: make lint-imports-root

    - name: Analyze imports within common/lib
      run: make lint-imports-common-lib

  pycodestyle:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Load requirements cache, if present
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/testing.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/edx/testing.txt

    - name: Check code style
      run: pycodestyle
